// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDew5RrGGG_ncyzIV2Mf4EWTfAqBcQ3kww',
    appId: '1:358157558122:web:3cca0864b0a882d4968513',
    messagingSenderId: '358157558122',
    projectId: 'reviewus-11434',
    authDomain: 'reviewus-11434.firebaseapp.com',
    storageBucket: 'reviewus-11434.appspot.com',
    measurementId: 'G-BRK3PQFWC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7_6J-J6O0Ndbf7KAQI5x_5AiL3MVuqlI',
    appId: '1:358157558122:android:6c97aab327fd9db9968513',
    messagingSenderId: '358157558122',
    projectId: 'reviewus-11434',
    storageBucket: 'reviewus-11434.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdVR4mFcguCxMdg5CYkKaSYn2JJoN44Iw',
    appId: '1:358157558122:ios:9ad154371e4235c6968513',
    messagingSenderId: '358157558122',
    projectId: 'reviewus-11434',
    storageBucket: 'reviewus-11434.appspot.com',
    iosClientId: '358157558122-fjr8q4dbsqac792mdj75m7mapsqntn93.apps.googleusercontent.com',
    iosBundleId: 'com.example.review',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdVR4mFcguCxMdg5CYkKaSYn2JJoN44Iw',
    appId: '1:358157558122:ios:9ad154371e4235c6968513',
    messagingSenderId: '358157558122',
    projectId: 'reviewus-11434',
    storageBucket: 'reviewus-11434.appspot.com',
    iosClientId: '358157558122-fjr8q4dbsqac792mdj75m7mapsqntn93.apps.googleusercontent.com',
    iosBundleId: 'com.example.review',
  );
}
